name: Spawn-Camp-Prevention
version: 0.1.0
main: com.gabezter4.asc.SC
commands:
  scp:
    description: Add and Remove command
    usage: /scp [add, remove, list, tool]
permissions:
  scp.admin:
    description: All permissions
    children:
        scp.remove: true
        scp.add: true
        scp.bypass: true
    default: op
  scp.bypass:
    description: Bypass the region guard
    default: op
  scp.add:
    description: Add command
    default: op
  scp.remove:
    description: Remove Command
    default: op
  scp.tool:
    description: Tool Command
    default: op